version: '3.7'

volumes:
  prometheus-data: {}

services:
  # sensor_simulator:
  #   build: ./sensor_simulator
    # Add any necessary configuration

  mqtt_broker:
    image: hivemq/hivemq4
    ports:
      - 1883:1883
      - 8000:8000
      - 8080:8080
      - 9399:9399
    volumes:
      - ./mqtt_broker/config/config.xml:/opt/hivemq/conf/config.xml
      - ./mqtt_broker/extensions/hivemq-mqtt-message-log-extension:/opt/hivemq/extensions/hivemq-mqtt-message-log-extension
      - ./mqtt_broker/extensions/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension

  prometheus:
    image: prom/prometheus
    volumes:
      - ./mqtt_broker/extensions/hivemq-prometheus-extension/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090  # Prometheus UI port

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000  # Grafana UI port
